#!/bin/bash

# set -e: don't tolerate non-zero exit status for any command
# set -u: only allow referencing of variables if they were previously defined
# set -o pipefail: prevent errors in a pipeline from being masked
set -euo pipefail

TAG=3.1.2-chrome-100-node-yarn-berry-wkhtmltopdf-ffmpeg

NAME=ghcr.io/denkungsart/ci-ruby:"$TAG"

docker build -t "$NAME" . &> logs/"$(date +%F)"-"$(date +%T)".log
