#!/bin/bash
set -xeo pipefail

IMAGEMAGICK_VERSION=${1:-7.1.0-39}

# ref https://imagemagick.org/script/install-source.php
wget "https://imagemagick.org/archive/ImageMagick.tar.gz"
tar xvzf "ImageMagick.tar.gz"
(
cd "ImageMagick-${IMAGEMAGICK_VERSION}/"
./configure --with-rsvg=yes
make
make install
ldconfig /usr/local/lib
)
