#!/bin/bash
set -xeo pipefail

apt-get update
apt-get install -y xfonts-75dpi xfonts-base

# download release from https://github.com/wkhtmltopdf/packaging/releases
wget "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb"
dpkg -i "wkhtmltox_0.12.6.1-2.bullseye_amd64.deb"
