#!/bin/bash
set -xeo pipefail

NODE_VERSION=${1:-11.x}

# ref https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash -

apt-get install -y nodejs
