#!/bin/bash
set -xeo pipefail

apt-get update

# psql required for database creation in test env
apt-get install -y postgresql-client

# cmake required for building of libgit2 and pronto
apt-get install -y cmake

# Watermarking dependencies for pdf files
apt-get install -y \
    pdftk \
    ghostscript
