#!/bin/bash
set -xeo pipefail

apt-get update

# psql required for database creation in test env
apt-get install -y postgresql-client

# image processing
apt-get install -y libvips42

# required by https://circleci.com/developer/orbs/orb/circleci/browser-tools
apt-get install -y jq

# Tools for transforming and inspecting PDF files
apt-get install -y \
    pdftk \
    ghostscript \
    poppler-utils

# Install qpdf 10.x
curl -o "/tmp/libqpdf28_10.1.0-1_${TARGETPLATFORM#*/}.deb" "https://ftp.debian.org/debian/pool/main/q/qpdf/libqpdf28_10.1.0-1_${TARGETPLATFORM#*/}.deb" \
  && dpkg -i "/tmp/libqpdf28_10.1.0-1_${TARGETPLATFORM#*/}.deb" \
  && rm "/tmp/libqpdf28_10.1.0-1_${TARGETPLATFORM#*/}.deb"
curl -o "/tmp/qpdf_10.1.0-1_${TARGETPLATFORM#*/}.deb" "https://ftp.debian.org/debian/pool/main/q/qpdf/qpdf_10.1.0-1_${TARGETPLATFORM#*/}.deb" \
  && dpkg -i "/tmp/qpdf_10.1.0-1_${TARGETPLATFORM#*/}.deb" \
  && rm "/tmp/qpdf_10.1.0-1_${TARGETPLATFORM#*/}.deb"
