#!/bin/bash
set -xeo pipefail

NODE_VERSION=${1:-8.x}

# add official debian repos for node
curl -sS -L https://deb.nodesource.com/setup_${NODE_VERSION} | bash -

apt-get update
apt-get install -y nodejs
