#!/usr/bin/env bash

CHROME_VERSION="116.0.5845.96"

if [[ $TARGETPLATFORM == "linux/amd64" ]]; then
  # ref https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries
  npx @puppeteer/browsers install chrome@stable
  npx @puppeteer/browsers install chromedriver@stable

  mv "/chrome/linux-$CHROME_VERSION/chrome-linux64/chrome" /usr/local/bin
  mv "/chromedriver/linux-$CHROME_VERSION/chromedriver-linux64/chromedriver" /usr/local/bin

  chrome --version && chromedriver --version
else
  echo "Chromium currently does not provide arm64 binaries for Linux"
fi
