name: Build & publish docker image
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Metadata action
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/denkungsart/ci-ruby
        tags: |
          type=ref,event=branch
    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.metadata.outputs.tags }}
